# Generated by Django 5.2.4 on 2025-07-18 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10)),
                ('primevue_theme', models.CharField(choices=[('aura', 'Aura'), ('lara', 'Lara'), ('nora', 'Nora'), ('material', 'Material')], default='aura', max_length=20)),
                ('menu_mode', models.CharField(choices=[('static', 'Static'), ('overlay', 'Overlay')], default='static', max_length=15)),
                ('primary_color', models.CharField(choices=[('amber', 'Amber'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('emerald', 'Emerald'), ('fuchsia', 'Fuchsia'), ('gray', 'Gray'), ('green', 'Green'), ('indigo', 'Indigo'), ('lime', 'Lime'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('rose', 'Rose'), ('sky', 'Sky'), ('slate', 'Slate'), ('stone', 'Stone'), ('teal', 'Teal'), ('violet', 'Violet'), ('yellow', 'Yellow'), ('zinc', 'Zinc')], default='emerald', max_length=10)),
                ('primary_tint', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='500', max_length=3)),
                ('surface_tint', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='500', max_length=3)),
                ('language', models.CharField(default='en-us', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
