
services:
  postgresql:
    image: postgres:17.5
    container_name: shrooDB
    environment:
      POSTGRES_DB: shroodb
      POSTGRES_USER: shroouser
      POSTGRES_PASSWORD: shroopassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myproject_user -d myproject_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgresql_data:
    driver: local